-- Seed data for tradeshows
INSERT INTO tradeshows (name, description, website, location, start_date, end_date, categories, image_url)
VALUES
  ('International Manufacturing Technology Show', 'One of the largest industrial trade shows in the world, featuring manufacturing technology.', 'https://www.imts.com', 'Chicago, IL', '2023-09-12', '2023-09-17', ARRAY['Manufacturing Technology', 'Industrial Automation', 'Tooling'], 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('FABTECH', 'North America''s largest metal forming, fabricating, welding and finishing event.', 'https://www.fabtechexpo.com', 'Atlanta, GA', '2023-11-08', '2023-11-10', ARRAY['Metal Fabrication', 'Welding', 'Finishing'], 'https://images.unsplash.com/photo-1565098772267-60af42b81ef2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Manufacturing & Technology Show', 'The premier event for manufacturing professionals looking to explore the latest technology innovations.', 'https://www.mfgtechshow.com', 'Cleveland, OH', '2023-06-20', '2023-06-22', ARRAY['Manufacturing Technology', 'Industry 4.0', 'Smart Manufacturing'], 'https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('PACK EXPO International', 'The world''s largest packaging trade show connecting professionals from consumer packaged goods companies.', 'https://www.packexpointernational.com', 'Las Vegas, NV', '2023-10-23', '2023-10-25', ARRAY['Packaging', 'Processing', 'Supply Chain'], 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Hannover Messe', 'The world''s leading trade show for industrial technology, showcasing innovations and solutions.', 'https://www.hannovermesse.de', 'Hannover, Germany', '2023-04-17', '2023-04-21', ARRAY['Industrial Technology', 'Automation', 'Energy Solutions'], 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Advanced Manufacturing East', 'The east coast''s premier advanced manufacturing event, connecting manufacturing professionals.', 'https://www.advmfgeast.com', 'New York, NY', '2023-06-13', '2023-06-15', ARRAY['Advanced Manufacturing', '3D Printing', 'Smart Factory'], 'https://images.unsplash.com/photo-1533417379565-6104a7124582?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80');

-- Seed data for publications
INSERT INTO publications (name, description, website, type, frequency, categories, image_url)
VALUES
  ('Manufacturing Engineering', 'The flagship publication of SME, covering manufacturing technology, trends, and best practices.', 'https://www.sme.org/me', 'Magazine', 'Monthly', ARRAY['Manufacturing Technology', 'Industry Trends', 'Best Practices'], 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Industry Week', 'Provides manufacturing leaders with insights, trends, and strategies for improving operations.', 'https://www.industryweek.com', 'Magazine', 'Monthly', ARRAY['Manufacturing Leadership', 'Operations', 'Technology'], 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Additive Manufacturing', 'Focused on industrial applications of 3D printing and additive manufacturing technologies.', 'https://www.additivemanufacturing.media', 'Magazine', 'Bi-monthly', ARRAY['3D Printing', 'Additive Manufacturing', 'Digital Manufacturing'], 'https://images.unsplash.com/photo-1581093196277-9f608bb3b1a1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Modern Machine Shop', 'Provides information on metalworking equipment, processes, and technologies.', 'https://www.mmsonline.com', 'Magazine', 'Monthly', ARRAY['Metalworking', 'CNC Machining', 'Tooling'], 'https://images.unsplash.com/photo-1565106430482-8f6e74349ca1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Manufacturing Business Technology', 'Covers technology solutions for manufacturing executives and decision-makers.', 'https://www.mbtmag.com', 'Magazine', 'Monthly', ARRAY['Manufacturing Technology', 'Business Solutions', 'Digital Transformation'], 'https://images.unsplash.com/photo-1573164713988-8665fc963095?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80');

-- Seed data for communities
INSERT INTO communities (name, description, website, type, size, categories, image_url)
VALUES
  ('Manufacturing Innovation Network', 'A global community of manufacturing professionals focused on innovation and technology adoption.', 'https://www.mininnovation.org', 'Hybrid', '10,000+', ARRAY['Innovation', 'Technology Adoption', 'Networking'], 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Women in Manufacturing', 'Supporting, promoting, and inspiring women in the manufacturing industry.', 'https://www.womeninmanufacturing.org', 'Hybrid', '5,000+', ARRAY['Women in Manufacturing', 'Diversity', 'Professional Development'], 'https://images.unsplash.com/photo-1573497701240-345a300b8d36?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Manufacturing Engineering Society', 'A professional community for manufacturing engineers to share knowledge and best practices.', 'https://www.manufacturingengineers.org', 'Online', '15,000+', ARRAY['Engineering', 'Professional Development', 'Knowledge Sharing'], 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Smart Manufacturing Forum', 'A community focused on the implementation of smart manufacturing technologies and Industry 4.0.', 'https://www.smartmanufacturingforum.com', 'Online', '8,000+', ARRAY['Smart Manufacturing', 'Industry 4.0', 'Digital Transformation'], 'https://images.unsplash.com/photo-1563770660941-10a63607692e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Sustainable Manufacturing Alliance', 'A community of manufacturers committed to sustainable practices and environmental responsibility.', 'https://www.sustainablemfg.org', 'Hybrid', '3,000+', ARRAY['Sustainability', 'Green Manufacturing', 'Environmental Responsibility'], 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80');

-- Seed data for organizations
INSERT INTO organizations (name, description, website, type, size, categories, image_url)
VALUES
  ('National Association of Manufacturers', 'The largest manufacturing association in the United States, representing small and large manufacturers in every industrial sector.', 'https://www.nam.org', 'Association', 'Large', ARRAY['Manufacturing Advocacy', 'Policy', 'Industry Representation'], 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Manufacturing Institute', 'The workforce development and education partner of the National Association of Manufacturers.', 'https://www.themanufacturinginstitute.org', 'Non-profit', 'Medium', ARRAY['Workforce Development', 'Education', 'Skills Training'], 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Society of Manufacturing Engineers', 'A professional organization dedicated to advancing manufacturing knowledge and influencing more than half a million manufacturing practitioners annually.', 'https://www.sme.org', 'Association', 'Large', ARRAY['Manufacturing Education', 'Professional Development', 'Knowledge Sharing'], 'https://images.unsplash.com/photo-1581092160607-ee22731c2eaf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Manufacturing USA', 'A network of regional institutes, each with a specialized technology focus, working to secure U.S. global leadership in advanced manufacturing.', 'https://www.manufacturingusa.com', 'Government', 'Large', ARRAY['Advanced Manufacturing', 'Innovation', 'Technology Development'], 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'),
  ('Association for Manufacturing Excellence', 'A not-for-profit organization dedicated to helping companies with continuous improvement and enterprise excellence.', 'https://www.ame.org', 'Association', 'Medium', ARRAY['Continuous Improvement', 'Lean Manufacturing', 'Operational Excellence'], 'https://images.unsplash.com/photo-1531758724865-26576625f97f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'); 